Repository TheaCOLINOT/git-project, pull requests merged in 2025-02, with the labels that each got.

#3 Setup/pr-template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, setup

#12 setup - Add husky hook
  .husky/pre-commit
  eslint.config.mjs
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
Labels: setup

#15 Add a Husky pre-commit
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .husky/pre-commit
  eslint.config.mjs
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
Labels: setup

#19 Add Workflow CI for the linter and test
  .github/workflows/ci.yml
Labels: setup

#20 Indentation correction ci.yml
  .env
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: bug, setup

#24 Add Home page
  src/page/Home.js
Labels: enhancement

#31 feature/structure-app - add app structure
  .env
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/components/Footer.js
  src/components/Header.js
  src/index.js
  src/logo.svg
  src/pages/Home.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/App.css
Labels: enhancement

#25 Add About page
  src/page/About.js
Labels: enhancement

#26 Add Contact page
  src/page/Contact.js
Labels: enhancement

#29 Rename code_of_conduct.md to CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: duplicate

#32 Feature/blog page
  .env
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  code_of_conduct.md
  package-lock.json
  package.json
  src/page/Blog.js
  src/page/Home.js
Labels: enhancement

#49 add css button contact page
  src/pages/Contact.js
  src/styles/Contact.css
Labels: bug
